#ifndef HOWBIGTHO
#define HOWBIGTHO

#define MAX_NUM_LEN 18
#define MATHSTR_LEN 50
#define MAX_EXP_CHARS 128
#define MAX_TREE_NODES 32
#define MAX_UI_BUTTONS 32
#define MAX_BG_NAME_CHARS 64
#define HASH_SEED 12345678
#define RAT_MATR_MAX 32

#endif